version: '2'

services:

  jupyter:
    build: .
    ports:
      - "8888:8888"
      - "4040-4080:4040-4080"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/work/data
    environment:
      - SPARK_OPTS="--master=local[*] --driver-memory=6g"
    command: start-notebook.sh --NotebookApp.iopub_data_rate_limit=1000000000
